apiVersion: v1 # Warning: v1 Endpoints is deprecated in v1.33+; use discovery.k8s.io/v1 EndpointSlice
kind: Service
metadata:
  name: sleep-service
spec:
  selector:
    app: sleep-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31080
  type: NodePort